[package]
name = "lunaship_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
chrono = "0.4.39"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
toml = "0.8.19"
